global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using PennySaver.API.Data;
global using PennySaver.API.Models;
global using System.Security.Claims;
global using System.Text;
global using System.Security.Cryptography;
global using System.IdentityModel.Tokens.Jwt;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.Extensions.Options;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using PennySaver.API.Services;
global using static PennySaver.API.Models.Account;